### PR TITLE
Support relative & absolute paths in .csproj

### PR DESCRIPTION
**Pull request by God-damnit-all**
Addresses https://github.com/DingoDjango/GrenadeFixRearmed/pull/3#issuecomment-672200493

### CODE REVIEW

**Comment by God-damnit-all** [comment]
Also moved the LICENSE file back into the root folder, oops.

**Comment by God-damnit-all** [comment]
Oh, I completely forgot the Manifest.xml and ModSync.xml files existed. Went ahead and updated those, too.

**Comment by DingoDjango** [comment]
Sure, thanks.

**Comment by DingoDjango** [comment]
The relative paths thing didn't work for me, sorry. Anyone who opens the proj can fix references in 2 minutes, so I doubt it's worth insisting on it.

**Comment by God-damnit-all** [comment]
It didn't fall back to the absolute paths when it couldn't find the relative paths?

**Comment by DingoDjango** [comment]
It's not about the references (I'm sure they work), just overall workflow (build events / build folder) and minimising variables that are unnecessary.

**Pull request merged**
